// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserService.proto

package UserService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RemoveTvDeviceRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	TvEmac               string   `protobuf:"bytes,2,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTvDeviceRequest) Reset()         { *m = RemoveTvDeviceRequest{} }
func (m *RemoveTvDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceRequest) ProtoMessage()    {}
func (*RemoveTvDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{0}
}

func (m *RemoveTvDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceRequest.Unmarshal(m, b)
}
func (m *RemoveTvDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceRequest.Merge(m, src)
}
func (m *RemoveTvDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceRequest.Size(m)
}
func (m *RemoveTvDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceRequest proto.InternalMessageInfo

func (m *RemoveTvDeviceRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *RemoveTvDeviceRequest) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

type RemoveTvDeviceResponse struct {
	IsTvDeviceRemoved    bool     `protobuf:"varint,1,opt,name=isTvDeviceRemoved,proto3" json:"isTvDeviceRemoved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTvDeviceResponse) Reset()         { *m = RemoveTvDeviceResponse{} }
func (m *RemoveTvDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceResponse) ProtoMessage()    {}
func (*RemoveTvDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{1}
}

func (m *RemoveTvDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceResponse.Unmarshal(m, b)
}
func (m *RemoveTvDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceResponse.Merge(m, src)
}
func (m *RemoveTvDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceResponse.Size(m)
}
func (m *RemoveTvDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceResponse proto.InternalMessageInfo

func (m *RemoveTvDeviceResponse) GetIsTvDeviceRemoved() bool {
	if m != nil {
		return m.IsTvDeviceRemoved
	}
	return false
}

type GetRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteReponse struct {
	IsDeleted            bool     `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReponse) Reset()         { *m = DeleteReponse{} }
func (m *DeleteReponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReponse) ProtoMessage()    {}
func (*DeleteReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{4}
}

func (m *DeleteReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReponse.Unmarshal(m, b)
}
func (m *DeleteReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReponse.Marshal(b, m, deterministic)
}
func (m *DeleteReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReponse.Merge(m, src)
}
func (m *DeleteReponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReponse.Size(m)
}
func (m *DeleteReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReponse proto.InternalMessageInfo

func (m *DeleteReponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type LinkedDeviceResponse struct {
	IsLinkedDeviceFetched bool            `protobuf:"varint,1,opt,name=isLinkedDeviceFetched,proto3" json:"isLinkedDeviceFetched,omitempty"`
	LinkedDevices         []*LinkedDevice `protobuf:"bytes,2,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-"`
	XXX_unrecognized      []byte          `json:"-"`
	XXX_sizecache         int32           `json:"-"`
}

func (m *LinkedDeviceResponse) Reset()         { *m = LinkedDeviceResponse{} }
func (m *LinkedDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*LinkedDeviceResponse) ProtoMessage()    {}
func (*LinkedDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{5}
}

func (m *LinkedDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDeviceResponse.Unmarshal(m, b)
}
func (m *LinkedDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDeviceResponse.Marshal(b, m, deterministic)
}
func (m *LinkedDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDeviceResponse.Merge(m, src)
}
func (m *LinkedDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_LinkedDeviceResponse.Size(m)
}
func (m *LinkedDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDeviceResponse proto.InternalMessageInfo

func (m *LinkedDeviceResponse) GetIsLinkedDeviceFetched() bool {
	if m != nil {
		return m.IsLinkedDeviceFetched
	}
	return false
}

func (m *LinkedDeviceResponse) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

type TvDevice struct {
	GoogleId             string        `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	LinkedDevice         *LinkedDevice `protobuf:"bytes,2,opt,name=linkedDevice,proto3" json:"linkedDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TvDevice) Reset()         { *m = TvDevice{} }
func (m *TvDevice) String() string { return proto.CompactTextString(m) }
func (*TvDevice) ProtoMessage()    {}
func (*TvDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{6}
}

func (m *TvDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TvDevice.Unmarshal(m, b)
}
func (m *TvDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TvDevice.Marshal(b, m, deterministic)
}
func (m *TvDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TvDevice.Merge(m, src)
}
func (m *TvDevice) XXX_Size() int {
	return xxx_messageInfo_TvDevice.Size(m)
}
func (m *TvDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_TvDevice.DiscardUnknown(m)
}

var xxx_messageInfo_TvDevice proto.InternalMessageInfo

func (m *TvDevice) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *TvDevice) GetLinkedDevice() *LinkedDevice {
	if m != nil {
		return m.LinkedDevice
	}
	return nil
}

type UpdateResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=isUpdated,proto3" json:"isUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

type CreateReponse struct {
	IsCreated            bool     `protobuf:"varint,1,opt,name=isCreated,proto3" json:"isCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReponse) Reset()         { *m = CreateReponse{} }
func (m *CreateReponse) String() string { return proto.CompactTextString(m) }
func (*CreateReponse) ProtoMessage()    {}
func (*CreateReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{8}
}

func (m *CreateReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReponse.Unmarshal(m, b)
}
func (m *CreateReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReponse.Marshal(b, m, deterministic)
}
func (m *CreateReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReponse.Merge(m, src)
}
func (m *CreateReponse) XXX_Size() int {
	return xxx_messageInfo_CreateReponse.Size(m)
}
func (m *CreateReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReponse proto.InternalMessageInfo

func (m *CreateReponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

type User struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	GoogleId             string               `protobuf:"bytes,4,opt,name=googleId,proto3" json:"googleId,omitempty"`
	Genre                []string             `protobuf:"bytes,5,rep,name=genre,proto3" json:"genre,omitempty"`
	Language             []string             `protobuf:"bytes,6,rep,name=language,proto3" json:"language,omitempty"`
	ContentType          []string             `protobuf:"bytes,7,rep,name=contentType,proto3" json:"contentType,omitempty"`
	LinkedDevices        []*LinkedDevice      `protobuf:"bytes,8,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *User) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *User) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *User) GetContentType() []string {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *User) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type LinkedDevice struct {
	TvEmac               string   `protobuf:"bytes,1,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	TvPanel              string   `protobuf:"bytes,2,opt,name=tvPanel,proto3" json:"tvPanel,omitempty"`
	TvBoard              string   `protobuf:"bytes,3,opt,name=tvBoard,proto3" json:"tvBoard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkedDevice) Reset()         { *m = LinkedDevice{} }
func (m *LinkedDevice) String() string { return proto.CompactTextString(m) }
func (*LinkedDevice) ProtoMessage()    {}
func (*LinkedDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{10}
}

func (m *LinkedDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDevice.Unmarshal(m, b)
}
func (m *LinkedDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDevice.Marshal(b, m, deterministic)
}
func (m *LinkedDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDevice.Merge(m, src)
}
func (m *LinkedDevice) XXX_Size() int {
	return xxx_messageInfo_LinkedDevice.Size(m)
}
func (m *LinkedDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDevice.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDevice proto.InternalMessageInfo

func (m *LinkedDevice) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

func (m *LinkedDevice) GetTvPanel() string {
	if m != nil {
		return m.TvPanel
	}
	return ""
}

func (m *LinkedDevice) GetTvBoard() string {
	if m != nil {
		return m.TvBoard
	}
	return ""
}

func init() {
	proto.RegisterType((*RemoveTvDeviceRequest)(nil), "UserService.RemoveTvDeviceRequest")
	proto.RegisterType((*RemoveTvDeviceResponse)(nil), "UserService.RemoveTvDeviceResponse")
	proto.RegisterType((*GetRequest)(nil), "UserService.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "UserService.DeleteRequest")
	proto.RegisterType((*DeleteReponse)(nil), "UserService.DeleteReponse")
	proto.RegisterType((*LinkedDeviceResponse)(nil), "UserService.LinkedDeviceResponse")
	proto.RegisterType((*TvDevice)(nil), "UserService.TvDevice")
	proto.RegisterType((*UpdateResponse)(nil), "UserService.UpdateResponse")
	proto.RegisterType((*CreateReponse)(nil), "UserService.CreateReponse")
	proto.RegisterType((*User)(nil), "UserService.User")
	proto.RegisterType((*LinkedDevice)(nil), "UserService.LinkedDevice")
}

func init() { proto.RegisterFile("UserService.proto", fileDescriptor_e7864342a5dd7108) }

var fileDescriptor_e7864342a5dd7108 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4b, 0x6f, 0x13, 0x31,
	0x10, 0x6e, 0xde, 0xc9, 0xa4, 0x8d, 0x88, 0x95, 0x94, 0x65, 0x41, 0x22, 0x98, 0x4b, 0x24, 0x60,
	0x2b, 0x15, 0x24, 0xb8, 0x14, 0x54, 0x28, 0x89, 0x10, 0x11, 0xaa, 0x42, 0x7a, 0x81, 0x93, 0x93,
	0x0c, 0xe9, 0x8a, 0xec, 0x83, 0x5d, 0x67, 0x25, 0xfe, 0x02, 0x12, 0xbf, 0x97, 0x2b, 0x5a, 0x7b,
	0x1f, 0x76, 0x5e, 0x84, 0x9b, 0xe7, 0x9b, 0x6f, 0xc6, 0xe3, 0x6f, 0x66, 0x0c, 0xed, 0x9b, 0x10,
	0x83, 0xcf, 0x18, 0x44, 0xf6, 0x0c, 0x2d, 0x3f, 0xf0, 0xb8, 0x47, 0x9a, 0x0a, 0x64, 0x3e, 0x5c,
	0x78, 0xde, 0x62, 0x89, 0x67, 0xc2, 0x35, 0x5d, 0x7d, 0x3b, 0xe3, 0xb6, 0x83, 0x21, 0x67, 0x8e,
	0x2f, 0xd9, 0xf4, 0x23, 0x74, 0xc7, 0xe8, 0x78, 0x11, 0x4e, 0xa2, 0x2b, 0x8c, 0x43, 0xc6, 0xf8,
	0x63, 0x85, 0x21, 0x27, 0x26, 0xd4, 0x65, 0xec, 0x87, 0xb9, 0x51, 0xe8, 0x15, 0xfa, 0x8d, 0x71,
	0x66, 0x93, 0x53, 0xa8, 0xf2, 0xe8, 0xbd, 0xc3, 0x66, 0x46, 0x51, 0x78, 0x12, 0x8b, 0x0e, 0xe0,
	0x74, 0x3d, 0x59, 0xe8, 0x7b, 0x6e, 0x88, 0xe4, 0x29, 0xb4, 0xed, 0x30, 0x47, 0x63, 0x8e, 0x4c,
	0x5b, 0x1f, 0x6f, 0x3a, 0x68, 0x1f, 0x60, 0x88, 0xfc, 0x80, 0x4a, 0xe8, 0x13, 0x38, 0xb9, 0xc2,
	0x25, 0xf2, 0x43, 0xca, 0xa6, 0xcf, 0x72, 0xb2, 0xac, 0xea, 0x01, 0x34, 0xec, 0x50, 0x42, 0x69,
	0x35, 0x39, 0x40, 0x7f, 0x17, 0xa0, 0x33, 0xb2, 0xdd, 0xef, 0x38, 0x5f, 0x7b, 0xcc, 0x0b, 0xe8,
	0xda, 0xa1, 0xea, 0x19, 0x20, 0x9f, 0xdd, 0x66, 0x29, 0xb6, 0x3b, 0xc9, 0x1b, 0x38, 0x59, 0x2a,
	0x70, 0x68, 0x14, 0x7b, 0xa5, 0x7e, 0xf3, 0xfc, 0x9e, 0xa5, 0xb6, 0x50, 0xbb, 0x4f, 0xe7, 0x53,
	0x84, 0x7a, 0x2a, 0xd4, 0xde, 0xee, 0x5c, 0xc0, 0xb1, 0x1a, 0x28, 0x7a, 0xb4, 0xf7, 0x1e, 0x8d,
	0x4e, 0x2d, 0x68, 0xdd, 0xf8, 0x73, 0xc6, 0xf3, 0xf7, 0x0a, 0x99, 0x24, 0xa6, 0xc8, 0x94, 0x00,
	0xb1, 0xaa, 0xef, 0x02, 0x64, 0x6b, 0xaa, 0x4a, 0x48, 0xa1, 0x27, 0x00, 0xfd, 0x53, 0x84, 0x72,
	0x5c, 0x09, 0x21, 0x50, 0x76, 0x99, 0x83, 0x49, 0xf9, 0xe2, 0x4c, 0x3a, 0x50, 0x41, 0x87, 0xd9,
	0xcb, 0x64, 0xae, 0xa4, 0x41, 0x7a, 0xd0, 0xf4, 0x6f, 0x3d, 0x17, 0x3f, 0xad, 0x9c, 0x29, 0x06,
	0x46, 0x49, 0xf8, 0x54, 0x48, 0x93, 0xa3, 0xbc, 0x26, 0x47, 0x07, 0x2a, 0x0b, 0x74, 0x03, 0x34,
	0x2a, 0xbd, 0x52, 0x9c, 0x53, 0x18, 0x71, 0xc4, 0x92, 0xb9, 0x8b, 0x15, 0x5b, 0xa0, 0x51, 0x15,
	0x8e, 0xcc, 0x8e, 0xef, 0x9b, 0x79, 0x2e, 0x47, 0x97, 0x4f, 0x7e, 0xfa, 0x68, 0xd4, 0x84, 0x5b,
	0x85, 0x36, 0x7b, 0x59, 0xff, 0xbf, 0x5e, 0x92, 0x57, 0xd0, 0x98, 0x49, 0x41, 0x2e, 0xb9, 0xd1,
	0x10, 0x0d, 0x32, 0x2d, 0x59, 0xb2, 0x95, 0xee, 0xaa, 0x35, 0x49, 0x77, 0x75, 0x9c, 0x93, 0xe3,
	0xc8, 0x95, 0x54, 0xfe, 0x92, 0x1b, 0xf0, 0xef, 0xc8, 0x8c, 0x4c, 0xbf, 0xc0, 0xb1, 0x5a, 0x92,
	0xb2, 0xc5, 0x05, 0x75, 0x8b, 0x89, 0x01, 0x35, 0x1e, 0x5d, 0x33, 0x17, 0xd3, 0x36, 0xa4, 0xa6,
	0xf4, 0xbc, 0xf5, 0x58, 0x30, 0x4f, 0x9a, 0x90, 0x9a, 0xe7, 0xbf, 0xca, 0xa0, 0xfe, 0x3b, 0xe4,
	0x02, 0x40, 0x36, 0x5c, 0xb4, 0xba, 0xad, 0xe9, 0x12, 0x9f, 0x4d, 0x53, 0x83, 0xb4, 0x01, 0xa2,
	0x47, 0xe4, 0x35, 0x80, 0x1c, 0xaf, 0x5d, 0xe1, 0xf7, 0x75, 0x48, 0x9b, 0x57, 0x7a, 0x44, 0x06,
	0x00, 0x72, 0x8b, 0x45, 0xbc, 0x7e, 0x97, 0xf6, 0x5f, 0x98, 0xdb, 0x7d, 0x69, 0x9e, 0x97, 0x50,
	0x1b, 0x22, 0x17, 0x49, 0xee, 0x6a, 0xc4, 0xfc, 0x7b, 0x32, 0x37, 0xab, 0xa3, 0x47, 0x64, 0x04,
	0x2d, 0xa9, 0x75, 0xb6, 0xb1, 0x5d, 0x8d, 0x96, 0xc2, 0xe6, 0xa3, 0xdd, 0x23, 0x93, 0x3f, 0xe7,
	0x2b, 0xb4, 0xf4, 0x7f, 0x95, 0x50, 0x2d, 0x6c, 0xeb, 0x0f, 0x6e, 0x3e, 0xde, 0xcb, 0xc9, 0x92,
	0x5f, 0xc3, 0x9d, 0x21, 0xf2, 0x91, 0x36, 0x9e, 0x3b, 0x1f, 0x7b, 0x48, 0xb9, 0xd3, 0xaa, 0x98,
	0xc3, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x2d, 0x11, 0xcd, 0x9d, 0x06, 0x00, 0x00,
}
